const charList = [
    //character, searches, picture
    ["Albedo", 55.3, "images/characters/albedo.webp"],
    ["Aloy", 0.2, "images/characters/aloy.webp"],
    ["Amber", 0.3, "images/characters/amber.webp"],
    ["Arataki Itto", 58, "images/characters/itto.webp"],
    ["Barbara", 6.9, "images/characters/barbara.webp"],
    ["Beidou", 15, "images/characters/beidou.webp"],
    ["Bennett", 92.1, "images/characters/bennett.webp"],
    ["Chongyun", 5.6, "images/characters/chongyun.webp"],
    ["Diluc", 8.4, "images/characters/diluc.webp"],
    ["Diona", 51.8, "images/characters/diona.webp"],
    ["Eula", 55.4, "images/characters/eula.webp"],
    ["Fischl", 25.2, "images/characters/fischl.webp"],
    ["Ganyu", 78.6, "images/characters/ganyu.webp"],
    ["Gorou", 15.8, "images/characters/gorou.webp"],
    ["Hu Tao", 70.6, "images/characters/hutao.webp"],
    ["Jean", 31.6, "images/characters/jean.webp"],
    ["Kazuha", 95, "images/characters/kazuha.webp"],
    ["Kaeya", 4.9, "images/characters/kaeya.webp"],
    ["Ayaka", 86.4, "images/characters/ayaka.webp"],
    ["Keqing", 7.1, "images/characters/keqing.webp"],
    ["Klee", 14.5, "images/characters/klee.webp"],
    ["Kujou Sara", 15.9, "images/characters/sara.webp"],
    ["Lisa", 1, "images/characters/lisa.webp"],
    ["Mona", 49.1, "images/characters/mona.webp"],
    ["Ningguang", 10.3, "images/characters/ningguang.webp"],
    ["Noelle", 9.3, "images/characters/noelle.webp"],
    ["Qiqi", 10, "images/characters/qiqi.webp"],
    ["Raiden Shogun", 91, "images/characters/raiden.webp"],
    ["Razor", 0.5, "images/characters/razor.webp"],
    ["Rosaria", 22.5, "images/characters/rosaria.webp"],
    ["Kokomi", 71.6, "images/characters/kokomi.webp"],
    ["Sayu", 1.7, "images/characters/sayu.webp"],
    ["Shenhe", 65.6, "images/characters/shenhe.webp"],
    ["Sucrose", 38, "images/characters/sucrose.webp"],
    ["Tartaglia", 40, "images/characters/tartaglia.webp"],
    ["Thoma", 10.4, "images/characters/thoma.webp"],
    ["Traveler", 3.4, "images/characters/traveler.webp"],
    ["Venti", 82.1, "images/characters/venti.webp"],
    ["Xiangling", 71.6, "images/characters/xiangling.webp"],
    ["Xiao", 48.4, "images/characters/xiao.webp"],
    ["Xingqiu", 90.7, "images/characters/xingqiu.webp"],
    ["Xinyan", 0.9, "images/characters/xinyan.webp"],
    ["Yanfei", 1.9, "images/characters/yanfei.webp"],
    ["Yae Miko", 62.9, "images/characters/yae.webp"],
    ["Yoimiya", 39.3, "images/characters/yoimiya.webp"],
    ["Yun Jin", 15.2, "images/characters/yunjin.webp"],
    ["Zhongli", 93.4, "images/characters/zhongli.webp"],
];